name: schedule-workflow

on:
  schedule:
    - cron: "19 18 * * *"


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: print message
        run: echo "schedule workflow executed"
    
